"""`kubekit decompile` — turn a notebook-authored pipeline into a production repo.

v1 is fully deterministic. No AI. Ugly but correct output. The AI layer
(better naming, component splitting suggestions, meaningful test assertions)
is a v2 concern — build the deterministic core first, pilot with a real
data scientist, then add intelligence informed by what they changed.

What this produces from a PipelineResult + recorded traces:

    <out_dir>/
    ├── README.md
    ├── Jenkinsfile
    ├── pyproject.toml
    ├── pipeline.py
    ├── components/
    │   ├── __init__.py
    │   ├── <component_1>.py
    │   └── ...
    └── tests/
        ├── __init__.py
        └── test_<component_1>.py

Every generated file has a header comment explaining that it was produced by
the decompiler and should be reviewed before merging. No magic wands.
"""
from __future__ import annotations

import inspect
import textwrap
from dataclasses import dataclass
from pathlib import Path

from kubekit_jupyter.pipeline import PipelineResult, get_component_registry
from kubekit_jupyter.traces import Trace, get_store


HEADER = """# Generated by `kubekit decompile` from a notebook-authored pipeline.
# Review before merging. The decompiler translates structure faithfully
# but cannot vouch for taste — names, boundaries, and tests should be
# checked by a human.
"""


@dataclass
class DecompileResult:
    out_dir: Path
    files_written: list[Path]

    def _repr_html_(self) -> str:
        files = "".join(f"<li><code>{p.relative_to(self.out_dir)}</code></li>" for p in self.files_written)
        return (
            f"<div style='padding:8px;border-left:3px solid #10b981;'>"
            f"<b style='color:#10b981;'>✓ decompiled to <code>{self.out_dir}</code></b>"
            f"<ul>{files}</ul></div>"
        )


def decompile(result: PipelineResult, out_dir: str | Path) -> DecompileResult:
    """Produce a production repo from a PipelineResult."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "components").mkdir(exist_ok=True)
    (out / "tests").mkdir(exist_ok=True)

    written: list[Path] = []
    written.append(_write_readme(out, result))
    written.append(_write_next_steps(out, result))
    written.append(_write_jenkinsfile(out, result))
    written.append(_write_pyproject(out, result))
    written.append(_write_pipeline_module(out, result))
    written.append(_write_init(out / "components"))
    written.append(_write_init(out / "tests"))

    store = get_store()
    for comp_name in result.components:
        written.append(_write_component_module(out, comp_name))
        written.append(_write_component_test(out, comp_name, store.for_component(comp_name)))

    return DecompileResult(out_dir=out, files_written=written)


# ---- individual emitters -------------------------------------------------


def _write_next_steps(out: Path, result: PipelineResult) -> Path:
    path = out / "NEXT_STEPS.md"
    missing = [c for c in result.components if not get_component_registry().get(c)]
    missing_note = ""
    if missing:
        bullets = "\n".join(f"- `components/{c}.py` (placeholder — paste body from notebook)" for c in missing)
        missing_note = (
            "\n## Components that still need bodies\n\n"
            "These components were referenced in the pipeline but no source was captured. "
            "Run the component cell with `%%kfp_component` in the source notebook and "
            "re-run `%kfp_decompile`, or paste the body in manually:\n\n"
            f"{bullets}\n"
        )

    lines = [
        f"# Next steps for {result.metadata.name}",
        "",
        "This repo was produced by `kubekit decompile` from a notebook-authored",
        "pipeline. The code is ready to review, but a few things need a human",
        "pass before you open a PR. Work through this checklist in order.",
        "",
        "## 1. Read the generated README",
        "",
        "Open `README.md` and confirm the pipeline name, owner, and component",
        "list match what you intended. If anything is wrong, fix it in the",
        "source notebook and re-run `%kfp_decompile` — do not edit the README",
        "by hand, it will be overwritten on the next decompile.",
        "",
        "## 2. Review each component",
        "",
        "Open every file in `components/`. For each one:",
        "",
        "- Does it have a resource spec (`cpu=`, `memory=`)?",
        "- Are all parameters type-annotated?",
        "- Does it use the platform logger instead of `print()`?",
        "- Are there no hardcoded credentials?",
        "",
        "The `%%kfp_component` magic already enforced these in the notebook,",
        "so they should all be yes. If anything looks off, something drifted",
        "between authoring and decompilation — mention it in your PR.",
        missing_note,
        "## 3. Fill in the regression tests",
        "",
        "Files in `tests/` were scaffolded from traces captured while you ran",
        "each component in the notebook. They currently assert `True` as a",
        "placeholder. Before merging, replace each `assert True` with a real",
        "correctness assertion about what the component should produce.",
        "",
        "## 4. Review `pipeline.py`",
        "",
        "Confirm the pipeline function is wired correctly and the component",
        "imports resolve. If the pipeline body is missing (a known v1 gap),",
        "paste it from the source notebook.",
        "",
        "## 5. Run tests locally",
        "",
        "    pip install -e .",
        "    pytest -q",
        "",
        "## 6. Open the PR",
        "",
        "    git init && git add . && git commit -m 'initial commit from kubekit decompile'",
        "    # push to your team's repo and open a PR",
        "",
        f"Tag {result.metadata.owner} as the owner. The team's review bot will run",
        "the standards audit automatically.",
        "",
        "## 7. After merge",
        "",
        "The Jenkins pipeline in `Jenkinsfile` will lint, test, audit, and submit",
        "to the platform on every merge to main. Watch the first run.",
        "",
    ]
    path.write_text("\n".join(lines))
    return path


def _write_readme(out: Path, result: PipelineResult) -> Path:
    path = out / "README.md"
    comps = "\n".join(f"- `components/{c}.py`" for c in result.components) or "- (none detected)"
    lines = [
        f"# {result.metadata.name}",
        "",
        f"Owner: {result.metadata.owner}",
        "",
        "Generated by `kubekit decompile` from a notebook-authored pipeline.",
        "Review before merging.",
        "",
        "## Pipeline",
        "",
        "The pipeline entry point is `pipeline.py`. It reconstructs the KFP v2",
        "pipeline that was authored and compiled in the source notebook.",
        "",
        "## Components",
        "",
        comps,
        "",
        "## Tests",
        "",
        "Regression tests in `tests/` were scaffolded from traces captured while",
        "the components were executed in the notebook. They assert structural",
        "properties (argument shapes, return types) observed during authoring.",
        "Add correctness assertions before merging.",
        "",
    ]
    path.write_text("\n".join(lines))
    return path


def _write_jenkinsfile(out: Path, result: PipelineResult) -> Path:
    path = out / "Jenkinsfile"
    body = textwrap.dedent(f"""
        // Generated by `kubekit decompile`.
        // This is the team's standard Jenkinsfile template — review and fill in.
        pipeline {{
            agent any
            environment {{
                PIPELINE_NAME = "{result.metadata.name}"
                PIPELINE_OWNER = "{result.metadata.owner}"
            }}
            stages {{
                stage('Lint')    {{ steps {{ sh 'ruff check .' }} }}
                stage('Test')    {{ steps {{ sh 'pytest -q' }} }}
                stage('Audit')   {{ steps {{ sh 'kubekit audit .' }} }}
                stage('Deploy')  {{ steps {{ sh 'kubekit submit pipeline.py' }} }}
            }}
        }}
    """).strip() + "\n"
    path.write_text(body)
    return path


def _write_pyproject(out: Path, result: PipelineResult) -> Path:
    path = out / "pyproject.toml"
    body = textwrap.dedent(f"""
        [project]
        name = "{result.metadata.name}"
        version = "0.1.0"
        requires-python = ">=3.10"
        dependencies = [
            "kfp>=2.0",
            "kubekit>=0.5",
        ]

        [tool.kubekit]
        owner = "{result.metadata.owner}"
    """).strip() + "\n"
    path.write_text(body)
    return path


def _write_pipeline_module(out: Path, result: PipelineResult) -> Path:
    path = out / "pipeline.py"
    from kubekit_jupyter.source import extract_function_source

    source = extract_function_source(
        result.pipeline_fn,
        fallback_cell=result.source or None,
    )

    # The recovered cell source already contains the imports the data
    # scientist wrote. Prepend just the component imports that the
    # decompiler knows about, and let the original source handle the rest.
    imports = "\n".join(f"from components.{c} import {c}" for c in result.components)

    if source:
        body = (
            HEADER
            + '"""Pipeline entry point for ' + result.metadata.name + '."""\n'
            + "import kubekit_jupyter as kubekit\n"
            + "from kfp import dsl\n"
            + (imports + "\n" if imports else "")
            + "\n"
            + source.rstrip() + "\n"
        )
    else:
        body = (
            HEADER
            + '"""Pipeline entry point for ' + result.metadata.name + '."""\n'
            + "import kubekit_jupyter as kubekit\n"
            + "from kfp import dsl\n"
            + (imports + "\n" if imports else "")
            + "\n"
            + f"# Could not recover source for {result.pipeline_fn.__name__}\n"
            + f"# Paste the pipeline body from the source notebook here.\n"
        )
    path.write_text(body)
    return path


def _write_component_module(out: Path, component_name: str) -> Path:
    path = out / "components" / f"{component_name}.py"
    record = get_component_registry().get(component_name)

    if record is not None and record.source:
        body = (
            HEADER
            + f'"""Component: {component_name}.\n\n'
            + f'Extracted from the source notebook by `kubekit decompile`.\n'
            + f'Review before merging.\n'
            + f'"""\n'
            + "from kfp import dsl\n"
            + "from kfp.dsl import Input, Output, Dataset, Model, Artifact  # noqa: F401\n\n"
            + record.source.rstrip() + "\n"
        )
    else:
        body = (
            HEADER
            + f'"""Component: {component_name} (not captured).\n\n'
            + f'No source was captured for this component. Run the component\n'
            + f'cell with `%%kfp_component` in the source notebook before\n'
            + f'running `%kfp_decompile`, or paste the body in manually.\n'
            + f'"""\n'
            + "from kfp import dsl\n\n"
            + f"def {component_name}(*args, **kwargs):\n"
            + f"    raise NotImplementedError(\n"
            + f"        'No source captured for {component_name}. See module docstring.'\n"
            + f"    )\n"
        )
    path.write_text(body)
    return path


def _write_component_test(out: Path, component_name: str, traces: list[Trace]) -> Path:
    path = out / "tests" / f"test_{component_name}.py"
    if not traces:
        body = (
            HEADER
            + f'"""Regression tests for {component_name} (no traces recorded)."""\n'
            + "import pytest\n\n"
            + f"def test_{component_name}_placeholder():\n"
            + f"    pytest.skip('No traces were recorded for {component_name}. Run the component in a notebook with %%kfp_component to capture traces.')\n"
        )
    else:
        cases = []
        for i, t in enumerate(traces):
            args_comment = "\n    ".join(f"# {k} = {v}" for k, v in t.args_repr.items())
            return_comment = f"# expected return shape: {t.return_repr}" if t.return_repr else "# return: None"
            cases.append(
                f"def test_{component_name}_trace_{i}():\n"
                f"    # Trace recorded during notebook execution.\n"
                f"    {args_comment}\n"
                f"    {return_comment}\n"
                f"    # TODO: replace with a real correctness assertion.\n"
                f"    assert True\n"
            )
        body = (
            HEADER
            + f'"""Regression tests for {component_name}, scaffolded from notebook traces."""\n\n'
            + "\n\n".join(cases)
        )
    path.write_text(body)
    return path


def _write_init(pkg_dir: Path) -> Path:
    path = pkg_dir / "__init__.py"
    path.write_text("")
    return path
